# Audio
AUDIO_FEATURE_DEEP_BUFFER_RINGTONE := true
AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := true
AUDIO_FEATURE_LOW_LATENCY_PRIMARY := true
BOARD_USES_ALSA_AUDIO := true
USE_CUSTOM_AUDIO_POLICY := 1

#Board features
AUDIO_FEATURE_ENABLED_FLUENCE := true
AUDIO_FEATURE_ENABLED_AUDIOSPHERE := true
BOARD_USES_SRS_TRUEMEDIA := true
DOLBY_DAP := true
DOLBY_DDP := true
AUDIO_FEATURE_ENABLED_DS1_DOLBY_DAP := true
DOLBY_UDC_MULTICHANNEL := true
DOLBY_UDC_STREAMING_HLS := true
AUDIO_PARAMETER_KEY_HD_VOICE := true
BOARD_HAS_AUDIO_DSP := true
